# Generated by Django 3.1.2 on 2021-04-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nazione', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tornei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('squadre', models.ManyToManyField(related_name='partecipanti', to='tornei.Squadre')),
            ],
        ),
    ]
