# Generated by Django 3.1.2 on 2021-04-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tornei', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tornei',
            options={'verbose_name': 'Tornei'},
        ),
    ]
