# Generated by Django 3.1.2 on 2021-04-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tornei', '0002_auto_20210414_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadre',
            name='livello',
            field=models.IntegerField(default=0),
        ),
    ]
