# Generated by Django 3.1.2 on 2021-04-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tornei', '0003_squadre_livello'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadre',
            options={'verbose_name': 'Squadra', 'verbose_name_plural': 'Squadre'},
        ),
        migrations.AlterModelOptions(
            name='tornei',
            options={'verbose_name': 'Torneo', 'verbose_name_plural': 'Tornei'},
        ),
    ]
